name: Build OpenWRT YouTube Live Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  OPENWRT_VERSION: "23.05.2"  # Updated to latest stable version

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up OpenWRT SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev unzip
        
        # Get latest SDK URL dynamically
        SDK_URL="https://downloads.openwrt.org/releases/${{ env.OPENWRT_VERSION }}/targets/x86/64/"
        SDK_FILE=$(curl -s $SDK_URL | grep -o 'openwrt-sdk-.*Linux-x86_64.tar.xz' | head -1)
        
        if [ -z "$SDK_FILE" ]; then
          echo "::error::Failed to find SDK file for OpenWRT ${{ env.OPENWRT_VERSION }}"
          exit 1
        fi
        
        echo "Downloading $SDK_FILE"
        wget "$SDK_URL$SDK_FILE" -O sdk.tar.xz
        tar xf sdk.tar.xz
        rm sdk.tar.xz
        mv openwrt-sdk-* openwrt-sdk
        echo "OPENWRT_SDK_PATH=$(pwd)/openwrt-sdk" >> $GITHUB_ENV

    - name: Prepare plugin
      run: |
        mkdir -p $OPENWRT_SDK_PATH/package/youtube-live
        cp -r Makefile src files $OPENWRT_SDK_PATH/package/youtube-live/
        cd $OPENWRT_SDK_PATH
        ./scripts/feeds update -a

    - name: Build plugin
      run: |
        cd $OPENWRT_SDK_PATH
        make defconfig
        make package/youtube-live/compile V=s -j$(nproc)
        mkdir -p $GITHUB_WORKSPACE/artifacts
        cp bin/packages/*/base/youtube-live*.ipk $GITHUB_WORKSPACE/artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: youtube-live-plugin
        path: artifacts/
        retention-days: 7
