name: Build OpenWRT YouTube Live Plugin with ImageBuilder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  OPENWRT_VERSION: "23.05.2"
  TARGET: "x86/64"  # Default target architecture

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: 'src'  # Mengekstrak repo ke folder 'src'

    - name: Setup OpenWRT ImageBuilder
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev unzip curl

        IB_URL="https://downloads.openwrt.org/releases/${{ env.OPENWRT_VERSION }}/targets/${{ env.TARGET }}/openwrt-imagebuilder-${{ env.OPENWRT_VERSION }}-${{ env.TARGET//\//- }}.Linux-x86_64.tar.xz"
        echo "Downloading ImageBuilder from: $IB_URL"
        
        wget "$IB_URL" -O imagebuilder.tar.xz || { echo "::error::Failed to download ImageBuilder"; exit 1; }
        tar xf imagebuilder.tar.xz || { echo "::error::Failed to extract ImageBuilder"; exit 1; }
        rm imagebuilder.tar.xz
        mv openwrt-imagebuilder-* openwrt-imagebuilder
        echo "IB_PATH=$(pwd)/openwrt-imagebuilder" >> $GITHUB_ENV

    - name: Prepare plugin package
      run: |
        # Copy seluruh isi repo ke package directory
        mkdir -p $IB_PATH/package/youtube-live
        cp -r src/* $IB_PATH/package/youtube-live/
        
        # Verifikasi file penting ada
        if [ ! -f "$IB_PATH/package/youtube-live/Makefile" ]; then
          echo "::error::Makefile not found in the repository"
          ls -la $IB_PATH/package/youtube-live/
          exit 1
        fi

    - name: Build package
      run: |
        cd $IB_PATH
        make package/youtube-live/compile V=s

    - name: Collect artifacts
      run: |
        mkdir -p $GITHUB_WORKSPACE/artifacts
        cp $IB_PATH/bin/packages/*/base/youtube-live*.ipk $GITHUB_WORKSPACE/artifacts/
        echo "IPK files:"
        ls -la $GITHUB_WORKSPACE/artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: youtube-live-plugin
        path: artifacts/
        retention-days: 7
