name: Build OpenWRT YouTube Live Plugin with ImageBuilder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  OPENWRT_VERSION: "23.05.2"  # Gunakan versi stabil terbaru

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup OpenWRT ImageBuilder
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev unzip curl

        # Download ImageBuilder
        IB_URL="https://downloads.openwrt.org/releases/${{ env.OPENWRT_VERSION }}/targets/x86/64/openwrt-imagebuilder-${{ env.OPENWRT_VERSION }}-x86-64.Linux-x86_64.tar.xz"
        echo "Downloading ImageBuilder from: $IB_URL"
        
        if ! wget "$IB_URL" -O imagebuilder.tar.xz; then
          echo "::error::Failed to download ImageBuilder"
          exit 1
        fi

        tar xf imagebuilder.tar.xz || { echo "::error::Failed to extract ImageBuilder"; exit 1; }
        rm imagebuilder.tar.xz
        mv openwrt-imagebuilder-* openwrt-imagebuilder
        echo "IB_PATH=$(pwd)/openwrt-imagebuilder" >> $GITHUB_ENV

    - name: Prepare plugin package
      run: |
        mkdir -p $IB_PATH/package/youtube-live
        cp -r Makefile src files $IB_PATH/package/youtube-live/

    - name: Build image with plugin
      run: |
        cd $IB_PATH
        make image PROFILE="generic" PACKAGES="youtube-live" EXTRA_IMAGE_NAME="with-youtube-live"

    - name: Collect artifacts
      run: |
        mkdir -p $GITHUB_WORKSPACE/artifacts
        cp $IB_PATH/bin/targets/x86/64/openwrt-*-with-youtube-live* $GITHUB_WORKSPACE/artifacts/
        cp $IB_PATH/bin/packages/x86_64/base/youtube-live*.ipk $GITHUB_WORKSPACE/artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-youtube-live
        path: artifacts/
        retention-days: 7
